name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        julia-version: ["1.6", "1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Use Julia cache
        uses: julia-actions/cache@v1
      - name: Run Pkg.build
        uses: julia-actions/julia-buildpkg@v1
      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@v1
      - name: Compute test coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Report coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
